<?php

return [
    'india' => [
        'Andaman and Nicobar Islands' => ['Port Blair'],
        'Andhra Pradesh' => ['Amaravati', 'Anantapur', 'Guntur', 'Kakinada', 'Kurnool', 'Nellore', 'Tirupati', 'Vijayawada', 'Visakhapatnam'],
        'Arunachal Pradesh' => ['Itanagar', 'Naharlagun', 'Pasighat', 'Tawang', 'Ziro'],
        'Assam' => ['Dibrugarh', 'Dispur', 'Guwahati', 'Jorhat', 'Silchar', 'Tezpur'],
        'Bihar' => ['Bhagalpur', 'Gaya', 'Muzaffarpur', 'Patna'],
        'Chandigarh' => ['Chandigarh'],
        'Chhattisgarh' => ['Bhilai', 'Bilaspur', 'Durg', 'Raipur'],
        'Dadra and Nagar Haveli and Daman and Diu' => ['Daman', 'Diu', 'Silvassa'],
        'Delhi' => ['New Delhi', 'Delhi'],
        'Goa' => ['Margao', 'Panaji', 'Vasco da Gama'],
        'Gujarat' => ['Ahmedabad', 'Anand', 'Bhavnagar', 'Gandhinagar', 'Jamnagar', 'Rajkot', 'Surat', 'Vadodara'],
        'Haryana' => ['Ambala', 'Faridabad', 'Gurugram', 'Hisar', 'Karnal', 'Panipat', 'Rohtak'],
        'Himachal Pradesh' => ['Dharamshala', 'Kullu', 'Manali', 'Shimla', 'Solan'],
        'Jammu and Kashmir' => ['Anantnag', 'Jammu', 'Srinagar'],
        'Jharkhand' => ['Bokaro Steel City', 'Dhanbad', 'Jamshedpur', 'Ranchi'],
        'Karnataka' => ['Belagavi', 'Bengaluru', 'Hubballi', 'Mangaluru', 'Mysuru', 'Udupi'],
        'Kerala' => ['Alappuzha', 'Kochi', 'Kollam', 'Kozhikode', 'Thiruvananthapuram', 'Thrissur'],
        'Ladakh' => ['Kargil', 'Leh'],
        'Lakshadweep' => ['Kavaratti'],
        'Madhya Pradesh' => ['Bhopal', 'Gwalior', 'Indore', 'Jabalpur', 'Ujjain'],
        'Maharashtra' => ['Aurangabad', 'Mumbai', 'Nagpur', 'Nashik', 'Pune', 'Solapur', 'Thane'],
        'Manipur' => ['Imphal'],
        'Meghalaya' => ['Shillong', 'Tura'],
        'Mizoram' => ['Aizawl', 'Lunglei'],
        'Nagaland' => ['Dimapur', 'Kohima'],
        'Odisha' => ['Bhubaneswar', 'Cuttack', 'Puri', 'Rourkela', 'Sambalpur'],
        'Puducherry' => ['Karaikal', 'Puducherry'],
        'Punjab' => ['Amritsar', 'Bathinda', 'Jalandhar', 'Ludhiana', 'Patiala'],
        'Rajasthan' => ['Ajmer', 'Bikaner', 'Jaipur', 'Jodhpur', 'Kota', 'Udaipur'],
        'Sikkim' => ['Gangtok', 'Namchi'],
        'Tamil Nadu' => ['Chennai', 'Coimbatore', 'Madurai', 'Salem', 'Tiruchirappalli', 'Tirunelveli'],
        'Telangana' => ['Hyderabad', 'Karimnagar', 'Khammam', 'Nizamabad', 'Warangal'],
        'Tripura' => ['Agartala'],
        'Uttar Pradesh' => ['Agra', 'Aligarh', 'Ghaziabad', 'Kanpur', 'Lucknow', 'Meerut', 'Noida', 'Prayagraj', 'Varanasi'],
        'Uttarakhand' => ['Dehradun', 'Haridwar', 'Nainital', 'Rishikesh', 'Roorkee'],
        'West Bengal' => ['Asansol', 'Durgapur', 'Howrah', 'Kolkata', 'Siliguri'],
    ],
];
