@php
    $panelType = 'admin';
    $panelLinks = [['label' => 'Overview', 'icon' => 'fas fa-grid-2', 'url' => route('admin.index')], ['label' => 'Products', 'icon' => 'fas fa-box', 'url' => route('admin.products.index')], ['label' => 'Customers', 'icon' => 'fas fa-users', 'url' => route('admin.users.index')], ['label' => 'Orders', 'icon' => 'fas fa-bag-shopping', 'url' => route('admin.orders.index')], ['label' => 'Payments', 'icon' => 'fas fa-credit-card', 'url' => route('admin.payments.index')]];
@endphp
@extends('layouts.panel')
@section('title', $order->order_number.' - ScentScape Admin')
@section('page_heading', 'Order Details')
@section('content')
    <div class="panel-welcome"><span class="panel-eyebrow">Order</span><h1>{{ $order->order_number }}</h1><p>{{ $order->user->name }} | {{ $order->user->email }} | Rs. {{ number_format((float) $order->total_amount, 2) }}</p></div>
    <section class="panel-card"><div class="panel-card-heading"><h2>Items</h2><a href="{{ route('admin.orders.index') }}">Back to orders</a></div>@if($order->items->isEmpty())<p class="panel-empty">This order does not include item records.</p>@else<div class="panel-table-wrap"><table class="panel-table"><thead><tr><th>Product</th><th>Quantity</th><th>Unit Price</th><th>Subtotal</th></tr></thead><tbody>@foreach($order->items as $item)<tr><td>{{ $item->product?->name ?? 'Product removed' }}</td><td>{{ $item->quantity }}</td><td>Rs. {{ number_format((float) $item->unit_price, 2) }}</td><td>Rs. {{ number_format((float) $item->subtotal, 2) }}</td></tr>@endforeach</tbody></table></div>@endif</section>
    <section class="panel-card"><div class="panel-card-heading"><h2>Manual Tracking</h2></div><form class="panel-form" method="POST" action="{{ route('admin.orders.update', $order) }}">@csrf @method('PUT')<div class="panel-form-grid"><label>Order Status<select name="status">@foreach(['pending', 'processing', 'shipped', 'delivered', 'cancelled'] as $status)<option value="{{ $status }}" @selected(old('status', $order->status) === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label>Payment Status<select name="payment_status">@foreach(['pending', 'paid', 'failed'] as $status)<option value="{{ $status }}" @selected(old('payment_status', $order->payment_status) === $status)>{{ ucfirst($status) }}</option>@endforeach</select></label><label>Courier Name<input name="courier_name" value="{{ old('courier_name', $order->courier_name) }}" placeholder="Delhivery, Blue Dart, etc."></label><label>Tracking Number<input name="tracking_number" value="{{ old('tracking_number', $order->tracking_number) }}" placeholder="Enter shipment tracking number"></label></div><label class="panel-full-field">Internal Notes<textarea name="notes" rows="5" placeholder="Delivery or payment notes for the admin team">{{ old('notes', $order->notes) }}</textarea></label><button class="panel-primary-btn" type="submit">Save Order Update</button></form></section>
    @if($order->shipping_address)<section class="panel-card"><div class="panel-card-heading"><h2>Delivery Address</h2></div><p class="admin-address">{{ $order->shipping_address['full_name'] ?? $order->user->name }}<br>{{ $order->shipping_address['address_line1'] ?? '' }} {{ $order->shipping_address['address_line2'] ?? '' }}<br>{{ $order->shipping_address['city'] ?? '' }}, {{ $order->shipping_address['state'] ?? '' }} {{ $order->shipping_address['pincode'] ?? '' }}<br>{{ $order->shipping_address['phone'] ?? '' }}</p></section>@endif
@endsection
